name: 'action-vbcable-win '
description: ''

runs:
  using: composite
  steps:

  - shell: powershell
    run: |
      $svc = Get-Service -Name audiosrv
      if ($svc.Status -ne 'Running') {
        Start-Service audiosrv
      }

  - shell: powershell
    run: |
      New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy\"
      New-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy" -Name "LetAppsAccessMicrophone" -Value "0x00000001" -PropertyType "dword"

  - shell: powershell
    run: |
      $RepoRoot = "${{ github.action_path }}" | Resolve-Path
      $UnzipDir = "$RepoRoot\VBCABLE_Temp"

      certutil -addstore TrustedPublisher "$RepoRoot\VBCABLE.cer"
      Expand-Archive "$RepoRoot\VBCABLE_Driver_Pack43.zip" -DestinationPath $UnzipDir
      . $RepoRoot\devcon install "$UnzipDir\vbMmeCable64_win7.inf" VBAudioVACWDM
