name: 'action-vbcable-win '
description: ''

runs:
  using: composite
  steps:

  - shell: cmd
    run: net start audiosrv

  - shell: powershell
    run: |
      certutil -addstore TrustedPublisher VBCABLE.cer
      Expand-Archive .\VBCABLE_Driver_Pack43.zip
      $DevConDir = "${env:ProgramFiles(x86)}\Windows Kits\10\tools\*\x64" | Resolve-Path
      . $DevConDir\devcon install VBCABLE_Driver_Pack43\vbMmeCable64_win7.inf VBAudioVACWDM
