name: 'action-vbcable-win '
description: ''

runs:
  using: composite
  steps:

  - shell: cmd
    run: net start audiosrv

  - shell: powershell
    run: |
      New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy\"
      New-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy" -Name "LetAppsAccessMicrophone" -Value "0x00000001" -PropertyType "dword"

  - shell: powershell
    run: |
      certutil -addstore TrustedPublisher "${{ github.action_path }}\VBCABLE.cer"

      $UnzipDir = "${{ github.action_path }}\VBCABLE_Temp"
      Expand-Archive "${{ github.action_path }}\VBCABLE_Driver_Pack43.zip" -DestinationPath $UnzipDir

      $DevConDir = "${env:ProgramFiles(x86)}\Windows Kits\10\tools\*\x64" | Resolve-Path
      . $DevConDir\devcon install "$UnzipDir\vbMmeCable64_win7.inf" VBAudioVACWDM
