name: 'action-vbcable-win '
description: ''

runs:
  using: composite
  steps:

  - shell: cmd
    run: net start audiosrv

  - shell: powershell
    run: |
      New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy\"
      New-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy" -Name "LetAppsAccessMicrophone" -Value "0x00000001" -PropertyType "dword"

  - shell: powershell
    run: |
      $RepoRoot = "${{ github.action_path }}" | Resolve-Path
      $UnzipDir = "$RepoRoot\VBCABLE_Temp"
      $DevConDir = "${env:ProgramFiles(x86)}\Windows Kits\10\tools\*\x64" | Resolve-Path

      certutil -addstore TrustedPublisher "$RepoRoot\VBCABLE.cer"
      Expand-Archive "$RepoRoot\VBCABLE_Driver_Pack43.zip" -DestinationPath $UnzipDir
      . $DevConDir\devcon install "$UnzipDir\vbMmeCable64_win7.inf" VBAudioVACWDM
