name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - uses: ./

    - run: choco install fmedia

    - run: fmedia --list-dev

    - run: |
        Start-Job -ScriptBlock { fmedia --repeat-all test.mp3 }
        fmedia --record --until=00:05 -o test-record.wav

    - uses: actions/upload-artifact@v4
      with:
        path: test-record.wav
