name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        certutil -addstore TrustedPublisher VBCABLE.cer
        Expand-Archive .\VBCABLE_Driver_Pack43.zip
        $DevConDir = "${env:ProgramFiles(x86)}\Windows Kits\10\tools\*\x64" | Resolve-Path
        . $DevConDir\devcon install VBCABLE_Driver_Pack43\vbMmeCable64_win7.inf VBAudioVACWDM

    - run: net start audiosrv

    - run: choco install fmedia

    - run: fmedia --list-dev
