name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/runner-images#available-images
        os: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - uses: ./

    - run: choco install fmedia

    - run: fmedia --list-dev

    - run: |
        Start-Job -ScriptBlock { fmedia --repeat-all test.mp3 }
        fmedia --record --until=00:05 -o test-record.wav

    - uses: actions/upload-artifact@v4
      with:
        path: test-record.wav
